In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('accounting_data.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Transaction ID                 1000 non-null   int64
 1   Date                           1000 non-null   object
 2   Account Type                   1000 non-null   object
 3   Transaction Amount             1000 non-null   int64
 4   Cash Flow                      1000 non-null   int64
 5   Net Income                     1000 non-null   int64
 6   Revenue                        1000 non-null   int64
 7   Expenditure                    1000 non-null   int64
 8   Profit Margin                  1000 non-null   float64
 9   Debt-to-Equity Ratio           1000 non-null   float64
 10  Operating Expenses             1000 non-null   int64
 11  Gross Profit                   1000 non-null   int64
 12  Transaction Volume             1000 non-null   int64
 13  Processing Time (seconds)      1000 non-null   float64
 14  Accuracy Score                 1000 non-null   float64
 15  Missing Data Indicator         1000 non-null   bool
 16  Normalized Transaction Amount  1000 non-null   float64
 17  Transaction Outcome            1000 non-null   int64
dtypes: bool(1), float64(5), int64(10), object(2)
memory usage: 133.9+ KB

In [3]:
# 1. Rename columns (Power BI-friendly, no spaces)
df.columns = [c.strip().replace(' ', '_').replace('(', '').replace(')', '')
              for c in df.columns]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Transaction_ID                 1000 non-null   int64
 1   Date                           1000 non-null   object
 2   Account_Type                   1000 non-null   object
 3   Transaction_Amount             1000 non-null   int64
 4   Cash_Flow                      1000 non-null   int64
 5   Net_Income                     1000 non-null   int64
 6   Revenue                        1000 non-null   int64
 7   Expenditure                    1000 non-null   int64
 8   Profit_Margin                  1000 non-null   float64
 9   Debt-to-Equity_Ratio           1000 non-null   float64
 10  Operating_Expenses             1000 non-null   int64
 11  Gross_Profit                   1000 non-null   int64
 12  Transaction_Volume             1000 non-null   int64
 13  Processing_Time_seconds        1000 non-null   float64
 14  Accuracy_Score                 1000 non-null   float64
 15  Missing_Data_Indicator         1000 non-null   bool
 16  Normalized_Transaction_Amount  1000 non-null   float64
 17  Transaction_Outcome            1000 non-null   int64
dtypes: bool(1), float64(5), int64(10), object(2)
memory usage: 133.9+ KB

In [4]:
# 2. Parse dates
df['Date']      = pd.to_datetime(df['Date'])
df['Month_Year']    = df['Date'].dt.to_period('M').astype(str)
df['Month']     = df['Date'].dt.strftime('%B')        # "January", "February" ...
df['Month_Num'] = df['Date'].dt.month                 # 1–12 for sort order in Power BI
df['Quarter']   = df['Date'].dt.quarter               # 1, 2, 3, 4
df['Year']      = df['Date'].dt.year                  # 2025, 2026 ...
df['DayOfWeek'] = df['Date'].dt.day_name()

df.head()

,Transaction_ID,Date,Account_Type,Transaction_Amount,Cash_Flow,Net_Income,Revenue,Expenditure,Profit_Margin,Debt-to-Equity_Ratio,...,Accuracy_Score,Missing_Data_Indicator,Normalized_Transaction_Amount,Transaction_Outcome,Month_Year,Month,Month_Num,Quarter,Year,DayOfWeek
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,...,0.959936,False,0.218724,1,2025-01,January,1,1,2025,Wednesday
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,...,0.966382,False,0.242232,1,2025-01,January,1,1,2025,Thursday
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,...,0.828307,False,0.993459,1,2025-01,January,1,1,2025,Friday
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,...,0.984149,False,0.927024,1,2025-01,January,1,1,2025,Saturday
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,...,0.929107,False,0.449509,1,2025-01,January,1,1,2025,Sunday

In [5]:
# 3. Normalise boolean flags
df['Missing_Data_Indicator'] = df['Missing_Data_Indicator'].astype(int)
df['Transaction_Outcome']    = df['Transaction_Outcome'].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Transaction_ID                 1000 non-null   int64
 1   Date                           1000 non-null   datetime64[ns]
 2   Account_Type                   1000 non-null   object
 3   Transaction_Amount             1000 non-null   int64
 4   Cash_Flow                      1000 non-null   int64
 5   Net_Income                     1000 non-null   int64
 6   Revenue                        1000 non-null   int64
 7   Expenditure                    1000 non-null   int64
 8   Profit_Margin                  1000 non-null   float64
 9   Debt-to-Equity_Ratio           1000 non-null   float64
 10  Operating_Expenses             1000 non-null   int64
 11  Gross_Profit                   1000 non-null   int64
 12  Transaction_Volume             1000 non-null   int64
 13  Processing_Time_seconds        1000 non-null   float64
 14  Accuracy_Score                 1000 non-null   float64
 15  Missing_Data_Indicator         1000 non-null   int64
 16  Normalized_Transaction_Amount  1000 non-null   float64
 17  Transaction_Outcome            1000 non-null   int64
 18  Month_Year                     1000 non-null   object
 19  Month                          1000 non-null   object
 20  Month_Num                      1000 non-null   int32
 21  Quarter                        1000 non-null   int32
 22  Year                           1000 non-null   int32
 23  DayOfWeek                      1000 non-null   object
dtypes: datetime64[ns](1), float64(5), int32(3), int64(11), object(4)
memory usage: 175.9+ KB

In [6]:
# 4. Round floats to 4 dp for readability
float_cols = df.select_dtypes('float64').columns
df[float_cols] = df[float_cols].round(4)

df.head()

,Transaction_ID,Date,Account_Type,Transaction_Amount,Cash_Flow,Net_Income,Revenue,Expenditure,Profit_Margin,Debt-to-Equity_Ratio,...,Accuracy_Score,Missing_Data_Indicator,Normalized_Transaction_Amount,Transaction_Outcome,Month_Year,Month,Month_Num,Quarter,Year,DayOfWeek
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.6072,2.0670,...,0.9599,0,0.2187,1,2025-01,January,1,1,2025,Wednesday
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.3556,2.3475,...,0.9664,0,0.2422,1,2025-01,January,1,1,2025,Thursday
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.6783,1.9010,...,0.8283,0,0.9935,1,2025-01,January,1,1,2025,Friday
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.2210,0.9341,...,0.9841,0,0.9270,1,2025-01,January,1,1,2025,Saturday
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.5093,1.0612,...,0.9291,0,0.4495,1,2025-01,January,1,1,2025,Sunday

In [7]:
# 5. Derived KPIs (add value for Power BI)
df['Net_Profit']    = df['Revenue'] - df['Expenditure']
df['OpEx_Ratio']    = (df['Operating_Expenses'] / df['Revenue']).round(4)
df['Success_Flag']  = df['Transaction_Outcome'].map({1:'Success', 0:'Failure'})

df.head()

,Transaction_ID,Date,Account_Type,Transaction_Amount,Cash_Flow,Net_Income,Revenue,Expenditure,Profit_Margin,Debt-to-Equity_Ratio,...,Transaction_Outcome,Month_Year,Month,Month_Num,Quarter,Year,DayOfWeek,Net_Profit,OpEx_Ratio,Success_Flag
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.6072,2.0670,...,1,2025-01,January,1,1,2025,Wednesday,1314,1.3063,Success
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.3556,2.3475,...,1,2025-01,January,1,1,2025,Thursday,1948,0.8249,Success
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.6783,1.9010,...,1,2025-01,January,1,1,2025,Friday,261,1.4213,Success
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.2210,0.9341,...,1,2025-01,January,1,1,2025,Saturday,3565,1.1315,Success
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.5093,1.0612,...,1,2025-01,January,1,1,2025,Sunday,4312,0.6636,Success

In [8]:
# 6. Validate — no negatives in Amount
assert (df['Transaction_Amount'] >= 0).all(), "Negative amounts found!"

In [9]:
# 7. Export CSV
df.to_csv('accounting_clean.csv', index=False)
print(f"Exported {len(df)} rows, {len(df.columns)} columns")

Exported 1000 rows, 27 columns